urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from core.views import *


urlpatterns = patterns('',
        url(r'^$', HomeView.as_view(), name="home"),
        url(r'^usuario/login/$', LogInView.as_view(), name="login"),
        url(r'^usuario/logout/$', LogOutView.as_view(), name="logout"),
        url(r'^usuario/login-error/$', LogInError.as_view(), name="login-error"),
        url(r'^usuario/$', login_required(ProfileView.as_view())),
        url(r'^usuario/renew-fb-session/$', login_required(RenewFacebookSession.as_view()), name="renew_fb_session"),
        .
        .
        .
        # Begin Groups
        url(r'^grupo/crear/$', login_required(GroupCreateView.as_view()), name="create_group"),
        url(r'^grupo/(?P<pk>\d+)/$', login_required(GroupWallView.as_view()), name="group"),
        url(r'^grupo/(?P<pk>\d+)/editar/$', login_required(GroupEditView.as_view()), name="edit_group"),
        url(r'^grupo/(?P<pk>\d+)/fotos/$', login_required(GroupPhotosView.as_view()),
           name="group_photos"),
        url(r'^grupo/(?P<pk>\d+)/invitar-amigos/$', login_required(GroupInviteFriendView.as_view()),
           name="group_invites"),
        .
        .
        .
        url(r'^grupo/(?P<pk>\d+)/invitar/$', login_required(GroupInviteView.as_view()), name="invite"),
        url(r'^grupo/(?P<pk>\d+)/invitados/$', login_required(GroupPossibleInvitesView.as_view()),
           name="group_possible_invites"),
        url(r'^grupo/(?P<pk>\d+)/subir-foto/$', login_required(GroupPhotoUploadView.as_view()),
           name="upload_group_photo"),
        url(r'^grupo/(?P<pk>\d+)/borrar-fotos$', login_required(GroupPhotoDeleteView.as_view()),
           name="delete_group_photo"),
        url(r'^grupo/(?P<pk>\d+)/abandonar/$', login_required(LeaveGroupView.as_view()), name="leave_group"),
        .
        .
        .
        # End Groups
        # Begin Hangouts
        url(r'^grupo/(?P<group_pk>\d+)/previa/crear/$', login_required(HangoutCreateView.as_view()),
           name="create_hangout"),
        url(r'^previa/(?P<pk>\d+)/$', login_required(HangoutWallView.as_view()),
            name="hangout"),
        url(r'^previa/(?P<pk>\d+)/editar/$', login_required(HangoutEditView.as_view()),
           name="edit_hangout"),
        url(r'^previa/(?P<pk>\d+)/invitar-grupos/$', login_required(HangoutInviteGroupView.as_view()),
           name="hangout_invites"),
        .
        .
        .
        # End Hangouts


)

models.py
# -*- encoding: utf-8 -*-
from datetime import timedelta
from math import floor
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.utils.datetime_safe import date, datetime
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractUser
from django.db import models
from sorl.thumbnail import get_thumbnail
from core.managers import GroupInvitationManager, UserManager, PendingActionManager, HangoutInvitationManager, \
    FriendsGroupManager, HangoutConfirmationAttendanceManager, HangoutManager
from core.notification_obtainer import NotificationObtainer

GENDER_CHOICES = (
    ('M', 'Hombre'),
    ('F', 'Mujer'),
)

INVITATION_STATUS_CHOICES = (
    ('P', 'Pendiente'),
    ('A', 'Aceptada'),
    ('R', 'Rechazada'),
)

RESPONSE_INVITATION_STATUS_CHOICES = (
    ('P', 'Pendiente'),
    ('C', 'Confirmado'),
    ('R', 'Rechazado'),
)



class FriendsGroup(models.Model):
    name = models.CharField(_(u'nombre'), max_length=200)
    area = models.CharField(_(u'zona'), max_length=200, blank=True)
    description = models.TextField(_(u'descripción'), max_length=1000, blank=True)
    members = models.ManyToManyField(User, related_name='friends_groups')
    image = models.ImageField(_(u'imagen'), upload_to='group_images', null=True, blank=True)
    wall = models.OneToOneField('core.GroupWall', related_name='group', null=True, blank=True)
    deleted = models.BooleanField(_(u'eliminado'), default=False)

    objects = FriendsGroupManager()

    def __unicode__(self):
        return self.name

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.wall:
            self.wall = GroupWall.new()

        return super(FriendsGroup, self).save(force_insert, force_update, using, update_fields)

    def remove(self):
        self.pending_invitations.all().delete()
        self.invitations.pending_invitations().delete()

        self.deleted = True
        self.save()

    def get_members(self):
        return self.members.all()

    def has_member(self, user):
        return self.members.filter(pk=user.pk).exists()

    def member_count(self):
        return self.members.count()

    def add_member(self, user):
        if self.has_member(user):
            raise Exception('User ' + str(user) + ' is already in group')

        self.members.add(user)

    def remove_member(self, user):
        if not self.has_member(user):
            raise Exception('User is not in group')

        if self.member_count() == 1 and self.has_created_a_hangout():
            raise Exception('Last member cannot leave when group created a hangout')

        self.members.remove(user)

        if self.members.count() == 0:
            self.remove()

    def age_average(self):
        all_members = self.get_members()
        member_count = 0
        age_sum = 0
        age_average = 0

        for member in all_members:
            if member.age:
                age_sum += member.age
                member_count += 1

        if member_count > 0:
            age_average = int(floor(age_sum/member_count))

        return age_average

    def all_pending_invitations(self):
        return self.invitations.filter(status='P')

    def all_pending_invitations_to_send(self):
        return self.pending_invitations.not_completed()

    def images(self):
        return self.image_library.all()

    def has_created_a_hangout(self):
        return self.created_hangouts.active().exists()

    def get_hangouts(self):
        return self.hangouts.active().all()

    def change_image(self, image_file):
        self.image.save(str(image_file), image_file)

    def get_image_thumbnail(self):
        im = get_thumbnail(self.image, "60x60", quality=90)
        return im.url


class GroupPhoto(models.Model):
    group = models.ForeignKey(FriendsGroup, related_name='image_library')
    image = models.ImageField(_(u'imagen'), upload_to='group_images')
    upload_date = models.DateTimeField(_(u'fecha de carga'), auto_now_add=True)

    def __unicode__(self):
        return u'Image: %s for: %s' % (self.image, self.group)

    @property
    def filename(self):
        return self.image.name

    @property
    def size(self):
        return self.image.size

    @property
    def url(self):
        return self.image.url

    def get_thumbnail(self):
        im = get_thumbnail(self.image, "80x80", quality=90)
        return im.url

    @classmethod
    def new_from_file(cls, file, group):
        photo = cls(group=group)
        photo.image.save(str(file), file)

        photo.save()

        return photo

.
.
.

class Wall(models.Model):
    def add_comment_from(self, sender, message_text):
        return WallComment.new_with(wall=self, sender=sender, message=message_text)

    @classmethod
    def new(cls):
        wall = cls()

        wall.full_clean()
        wall.save()

        return wall


class UserWall(Wall):
    class Meta:
        proxy = True

    def __init__(self, *args, **kwargs):
        self.notification_manager = NotificationObtainer(
            notification_types=[GroupWallCommentNotification, HangoutWallCommentNotification,
                                GroupInvitationAcceptedNotification, HangoutAttendanceConfirmedNotification,
                                HangoutAttendanceRejectedNotification, UserLeftGroupNotification])

        super(UserWall, self).__init__(*args, **kwargs)

    def add_comment_from(self, sender, message_text):
        raise Exception('Cannot comment on user wall')

    def all_messages(self):
        return self.notification_manager.get_all_notifications_of(self.user)

    def get_n_messages(self, n):
        return self.notification_manager.get_n_notifications_of(self.user, n=n)


class GroupWall(Wall):
    class Meta:
        proxy = True

    def __init__(self, *args, **kwargs):
        self.notification_manager = NotificationObtainer(
            notification_types=[GroupInvitationAcceptedNotification, HangoutInvitationNotification,
                                UserLeftGroupNotification])

        super(GroupWall, self).__init__(*args, **kwargs)

    def notifications_of(self, user):
        return self.notification_manager.get_all_notifications_of(user, action__group=self.group)

    def all_comments(self):
        return list(self.comments.all())

    def _sort_messages(self, messages):
        messages.sort(key=lambda message: message.date, reverse=True)

    def all_messages_of(self, user):
        notifications = self.notifications_of(user)
        comments = self.all_comments()

        messages = notifications + comments

        self._sort_messages(messages)

        return messages


class HangoutWall(Wall):
    class Meta:
        proxy = True

    def __init__(self, *args, **kwargs):
        self.notification_manager = NotificationObtainer(
            notification_types=[HangoutAttendanceConfirmedNotification, HangoutAttendanceRejectedNotification,
                                HangoutInvitationNotification])

        super(HangoutWall, self).__init__(*args, **kwargs)

    def notifications_of(self, user):
        return self.notification_manager.get_all_notifications_of(user, action__hangout=self.hangout)

    def all_comments(self):
        return list(self.comments.all())

    def _sort_messages(self, messages):
        messages.sort(key=lambda message: message.date, reverse=True)

    def all_messages_of(self, user):
        notifications = self.notifications_of(user)
        comments = self.all_comments()

        messages = notifications + comments

        self._sort_messages(messages)

        return messages


class WallComment(models.Model):
    wall = models.ForeignKey(Wall, related_name='comments')
    sender = models.ForeignKey(User, related_name='wall_comments')
    message = models.TextField(_(u'texto'), max_length=2000, blank=False)
    date = models.DateTimeField(_(u'fecha'), auto_now=True)

    def __unicode__(self):
        return u'Message of %s in %s ' % (self.sender, self.wall)

    @classmethod
    def new_with(cls, wall, sender, message):
        message = cls(wall=wall, sender=sender, message=message)

        message.full_clean()
        message.save()

        return message

templates/edit_group.html
{% extends 'group_layout.html' %}

{% load i18n %}
{% load image_tags %}
{% load thumbnail %}

{% block group_tabs %}
    <div class="solapas">
        <a href="{% url 'group' group.pk %}"><div class="solapa muro"><img src="{{ STATIC_URL }}img/muro.png" /></div></a>
        <a href="{% url 'group_photos' group.pk %}"><div class="solapa fotos"><img src="{{ STATIC_URL }}img/fotos.png" /></div></a>
        <a href="{% url 'group_invites' group.pk %}"><div class="solapa amigos"><img src="{{ STATIC_URL }}img/invitar-usuario.png" /></div></a>
        <a href="#"><div class="solapa config activo"><img src="{{ STATIC_URL }}img/config.png" /></div></a>
    </div>
{% endblock %}

{% block group_right_container %}
    <div class="grupo-config">
        <div>
            <h1>{% trans 'configuración del perfil de grupo' %}</h1>
            <a class="abandonar-grupo" href="{% url "leave_group" group.pk %}">abandonar grupo</a>
        </div>

        <form id="form-imagen" class="form-grupo" method="post" enctype="multipart/form-data">
            <div id='contenedor-cambiar-foto' class="form_field cambiar-foto">
                <a id="cambiar_foto" href="#" class="boton1">cambiar foto de perfil</a>
                {% thumbnail group.image '60x60' crop='center' as group_image %}
                    <img class="foto-grupo" src="{{ group_image.url }}" width="{{ group_image.width }}" height="{{ group_image.height }}">
                {% empty %}
                    <img class="foto-grupo" src="{% default_group_picture %}" width="60" height="60">
                {% endthumbnail %}
                <input id="id_image" name="image" type="file" class="boton3" style="display: none;">
                <div class="ajustar"></div>
            </div>
        </form>

        <form id="form-imagen" class="form-grupo" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form_field">
                <label
                        {% if form.name.errors %} class="form-error" {% endif %}
                        for="id_name">{% trans 'Nombre' %}
                </label>
                {{ form.name }}
            </div>

            <div class="form_field">
                <label for="id_area">{% trans 'Zona' %}</label>
                {{ form.area }}
            </div>

            <div class="form_field">
                <label for="id_description">{% trans 'Descripción' %}</label><br>
                <textarea id="id_description" name="description" rows="5">{{ group.description }}</textarea>
            </div>

            {% if form.errors %}
                <p class="form-error">revise los campos y vuelva a intentarlo</p>
            {% endif %}
            <input class="boton2" type="submit" value="guardar">
        </form>
    </div>
{% endblock %}

{% block extra_js %}
    {{ block.super }}
    <script type="text/javascript">
        $(document).ready(function() {
            var spinner = new Spinner({
                top: 13,
                left: 13,
                color: '#fff',
                radius: 8,
                width: 2 });

            $('#cambiar_foto').click(function(event) {
                event.preventDefault();
                $('#id_image').click();
            });

            $('#form-imagen').fileupload({
                url: "{% url 'change_group_image' group.pk %}",
                dataType: 'json',
                start: function() {
                    var profileImageContainer = document.getElementById('contenedor-cambiar-foto');
                    spinner.spin(profileImageContainer);
                },
                done: function(e, data) {
                    spinner.stop();

                    var newImage = data.result.files[0];
                    $('.foto-grupo').attr('src', newImage.thumbnail_url);
                }
            });
        });
    </script>
{% endblock %}

templates/edit_profile.html
{% extends 'profile_layout.html' %}

{% load i18n %}
{% load image_tags %}
{% load thumbnail %}

{% block title %}| {{ profile_user.get_full_name }}{% endblock %}

{% block profile_left_container %}
    <a class="boton-perfil" href="{% url 'profile' %}">notificaciones</a>
    <a class="boton-perfil" href="{% url 'profile_groups' %}">grupos</a>
    <a class="boton-perfil" href="{% url 'profile_hangouts' %}">previas</a>
    <a class="boton-perfil activo" href="#">configuración</a>
    <a class="boton-perfil" href="{% url 'profile_friends_groups' %}">ver grupos</a>
    <a class="boton-perfil recomendar" href="{% url 'profile_site_invitations' %}">recomendá sale previa</a>
    <a class="boton2 boton-crear" href="{% url 'create_group' %}">+ crear grupo</a>
{% endblock %}

{% block profile_right_container %}
    <div class="panel-derecho grupo-muro">
        <div class="grupo-config">
            <div>
                <h1>{% trans 'configuración de perfil' %}</h1>
            </div>

            <form id="form-imagen" class="form-grupo" method="post" enctype="multipart/form-data">
                <div id="contenedor-cambiar-foto" class="form_field cambiar-foto">
                    <a id="cambiar_foto" href="#" class="boton3">cambiar foto de perfil</a>
                    {% thumbnail user.profile_image '60x60' crop='center' as member_image %}
                        <img class="foto-miembro" src="{{ member_image.url }}" width="{{ member_image.width }}" height="{{ member_image.height }}" />
                    {% empty %}
                        <img class="foto-miembro" src="{% default_profile_picture %}" width="60" height="60" />
                    {% endthumbnail %}
                    <input id="id_profile_image" name="profile_image" type="file" class="boton3" style="display: none;">
                    <div class="ajustar"></div>
                </div>
            </form>

            <form id="form-grupo" class="form-grupo" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form_field">
                    <label
                            {% if form.first_name.errors %} class="form-error" {% endif %}
                            for="id_first_name">{% trans 'Nombre' %}:
                    </label>
                    {{ form.first_name }}
                </div>

                <div class="form_field">
                    <label
                            {% if form.last_name.errors %} class="form-error" {% endif %}
                            for="id_last_name">{% trans 'Apellido' %}:
                    </label>
                    {{ form.last_name }}
                </div>

                <div class="form_field">
                    <label for="id_gender">{% trans 'Sexo' %}:</label>
                    {{ form.gender }}
                </div>

                <div class="form_field">
                    <label for="id_neighbourhood">{% trans 'Localidad' %}:</label>
                    {{ form.neighbourhood }}
                </div>

                <div class="form_field">
                    <label for="id_city">{% trans 'Ciudad' %}:</label>
                    {{ form.city }}
                </div>

                <div class="form_field">
                    <label for="id_province">{% trans 'Provincia' %}:</label>
                    {{ form.province }}
                </div>

                <div id="dp3" class="form_field input-append date" data-date="12-02-2012" data-date-format="dd/mm/yyyy">
                    <label for="id_birth_date">{% trans 'Fecha de nacimiento' %}:</label>
                    <input id="id_birth_date" name="birth_date" type="text" value=" {{ form.birth_date.value|date:"d/m/Y" }}" readonly>
                    <span class="add-on">
                        <i class="icon-th"></i>
                    </span>
                </div>

                <div class="form_field">
                    <label for="id_description">{% trans 'Descripción' %}:</label>
                    {{ form.description }}
                </div>

                {% if form.errors %}
                    {% for error in form.non_field_errors %}
                        <p class="form-error">{{ error }}</p>
                    {% endfor %}
                    <p class="form-error">revise los campos y vuelva a intentarlo</p>
                {% endif %}
                <input class="boton1" type="submit" value="guardar">
            </form>
        </div>
    </div>
{% endblock %}

{% block extra_js %}

    <script type="text/javascript">
        $(document).ready(function() {
            var spinner = new Spinner({
                    top: 13,
                    left: 13,
                    color: '#fff',
                    radius: 8,
                    width: 2 });

            $('#cambiar_foto').click(function(event) {
                event.preventDefault();
                $('#id_profile_image').click();
            });
            $('#dp3').datepicker();

            $('#form-imagen').fileupload({
                url: "{% url 'change_profile_image' %}",
                dataType: 'json',
                start: function() {
                    var profileImageContainer = document.getElementById('contenedor-cambiar-foto');
                    spinner.spin(profileImageContainer);
                },
                done: function(e, data) {
                    spinner.stop();

                    var newImage = data.result.files[0];
                    $('.foto-miembro').attr('src', newImage.thumbnail_url);
                }
            });
        });
    </script>
{% endblock %}

templates/group_wall.html
{% extends 'group_layout.html' %}

{% load i18n %}
{% load image_tags %}
{% load wall_tags %}

{% block title %}| {{ group.name }}{% endblock %}

{% block group_tabs %}
    <div class="solapas">
        <a href="#"><div class="solapa muro activo"><img src="{{ STATIC_URL }}img/muro.png" /></div></a>
        <a href="{% url 'group_photos' group.pk %}"><div class="solapa fotos"><img src="{{ STATIC_URL }}img/fotos.png" /></div></a>
        <a href="{% url 'group_invites' group.pk %}"><div class="solapa amigos"><img src="{{ STATIC_URL }}img/invitar-usuario.png" /></div></a>
        <a href="{% url 'edit_group' group.pk %}"><div class="solapa config"><img src="{{ STATIC_URL }}img/config.png" /></div></a>
    </div>
{% endblock %}

{% block group_right_container %}
    <div class="grupo-muro">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form_field">
                <textarea id="id_message" name="message" placeholder="{% trans 'Escribí tu mensaje aquí...' %}"></textarea>
                <input class="publicar boton1" type="submit" value="{% trans 'publicar' %} >"/>
            </div>


            {% if wall_messages|length > 0 %}
                <div class="ajustar post"></div>
            {% endif %}


        <div class="endless_page_template">
            {% include group_wall_messages_page %}
        </div>
        {% block js %}
            {{ block.super }}
            <script src="{{ STATIC_URL }}endless_pagination/js/endless-pagination.js"></script>
            <script>
                $.endlessPaginate({
                    paginateOnScroll: true,
                    paginateOnScrollMargin: 20,
                    paginateOnScrollChunkSize: 5
                });
            </script>
        {% endblock %}


        </form>
    </div>
{% endblock %}

templates/group_wall_messages_page.html
{% load i18n %}
{% load wall_tags %}
{% load endless %}

{% paginate wall_messages %}
{% for wall_message in wall_messages %}
    {% show_group_wall_message wall_message %}
{% empty %}
    <p>{% trans 'No hay mensajes en el muro del grupo' %}</p>
{% endfor %}
{% show_more %}